version: "3"
services:
  node-simile:
    build: 
      context: .
      args:
        NODE_ENV: production
    ports:
      - "5000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - MONGO_USER=user
      - MONGO_PASSWORD=user
      - SESSION_SECRET=secret
    command: npm run start