version: "3"
services:
  node-simile:
    build: .
    container_name: node4${COMPOSE_PROJECT_NAME}
    ports:
      - 8083:${WEBGIS_PORT}
    environment:
      - PORT=${WEBGIS_PORT}
      - ENVIRONMENT=${NODE_ENV}
      - SITE_URL=${SITE_URL}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    depends_on:
      - mongo-simile
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start
    env_file:
      - .env
  mongo-simile:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-db-simile:/data/db
    env_file:
      - .env
  redis-simile:
    image: redis
    env_file:
      - .env
volumes:
  mongo-db-simile: 