version: "3"
services:
  node-simile:
    build: 
      context: .
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=user
      - MONGO_PASSWORD=user
      - SESSION_SECRET=secret
    command: npm run dev

    
  mongo-simile:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=user