version: "3"
services:
  node-simile:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo-simile
  mongo-simile:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=user
    volumes:
      - mongo-db-simile:/data/db
  redis-simile:
    image: redis
volumes:
  mongo-db-simile: 